### ISSUE TITLE
Missing handling of localized file name of dependent files

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/texture#103]
File names are handled as non-localized data, which was changed in OJS 3.3.
This leads to broken links to figures when reading the file as well as incorrect data of uploaded ones.
Associated error in the log when opening JATS XML with attached image:
```
PHP Warning:  Illegal offset type in /home/doc/OJS/development/versions/ojs-3.3.0-8/plugins/generic/texture/classes/DAR.inc.php on line 204
```
Uploading the image through the plugin leads to incorrect database entry in `submission_file_settings` table:
```
submission_file_id	locale	setting_name	setting_value	setting_type	

2466	0	name	fig4_2.jpg	string
```

Tested with OJS 3.3.0 and main branch of the Texture plugin

**Comment by Vitaliy-1** [comment]
PR: https://github.com/pkp/texture/pull/104

**Comment by Vitaliy-1** [comment]
@withanage, can you take a look?

**Comment by withanage** [comment]
@Vitaliy-1  thanks, I have tested the  enhancements and merged.
