### ISSUE TITLE
Texture supports chrome browser warning

### ISSUE THREAD

**Issue by NateWr** [pkp/texture#86]
There's a warning that appears when using Texture in Firefox that says Texture only supports Chrome. Do we know what limitations are faced in other browsers?

**Comment by withanage** [comment]
- [ ]  In Firefox, I never had any problems.

With edge , I never tested, cause substance developers generally did not support windows operating system. (also in lens)

**Comment by withanage** [comment]
-   In Firefox  it works, although the  warning was there. :ok: 
- In Edge it worked in some versions.
- In Internet explorer, it never worked.

**Comment by NateWr** [comment]
Can we just remove the warning altogether? I don't want us to endorse Chrome usage as the "right way"...

**Comment by withanage** [comment]
As Substance developers strongly focused on chrome, there can be still  problems with other browsers,  may be would it make sense to change the  wording there, if it is not chrome or browser e.g. something in the direction
"This  software may have limited functionality on your browser. Following browsers are fully supported: firefox, chrome"

I didn't test under apple OS, may be good, if we could at least test safari

**Comment by NateWr** [comment]
Yeah, I like that phrasing. Let's try:

> This editor may may not work fully in your browser. If you experience problems, please try loading the editor in Firefox or Chrome.

**Comment by withanage** [comment]
sure, that sounds good. I will work on the texture editor js developments  and will send you the changes in a a  PR in one go.
