### ISSUE TITLE
fails on OJS 3.3.0.2. undefined method SubmissionFile::getExtension()

### ISSUE THREAD

**Issue by marcoblancas** [pkp/texture#96]
When OJS is "loading files" in the production phase (I suppose the same in other phases), the page never ends "loading files" and I get this error in apache logs:

> [Sun Feb 07 20:46:50.849739 2021] [php7:error] [pid 13397] [client 127.0.0.1:46010] PHP Fatal error:  Uncaught Error: Call to undefined method SubmissionFile::getExtension() in /home/isaac.marco/git/ojs33/plugins/generic/texture/TexturePlugin.inc.php:130\nStack trace:\n#0 /home/isaac.marco/git/ojs33/lib/pkp/classes/plugins/HookRegistry.inc.php(107): TexturePlugin->templateFetchCallback('TemplateManager...', Array)\n#1 /home/isaac.marco/git/ojs33/lib/pkp/classes/template/PKPTemplateManager.inc.php(1070): HookRegistry::call('TemplateManager...', Array)\n#2 /home/isaac.marco/git/ojs33/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1020): PKPTemplateManager->fetch('controllers/gri...')\n#3 /home/isaac.marco/git/ojs33/lib/pkp/classes/controllers/grid/GridHandler.inc.php(986): GridHandler->renderRowInternally(Object(Request), Object(SubmissionFilesGridRow))\n#4 /home/isaac.marco/git/ojs33/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1031): GridHandler->renderRowsInternally(Object(Request), Array)\n#5 /home/isaac.marco/git/ojs33/lib/pkp/classes/controllers/grid/GridHandler.inc.php(921): GridHandler->renderGri in /home/isaac.marco/git/ojs33/plugins/generic/texture/TexturePlugin.inc.php on line 130, referer: http://loc.ojs33/index.php/cero/workflow/index/3/5

**Comment by asmecher** [comment]
@marcoblancas, this is caused by using a version of the Texture plugin that's not compatible with OJS 3.3.0. Watch for a Texture plugin release for 3.3.x to appear soon, and in the meantime, you'll need to disable it.
